### ISSUE TITLE
Fatal SocketTimeoutException

### ISSUE THREAD

**Issue by ali-star** [Notificare/notificare-sdk-android#104]
Hi, we have this crash for a while now:
```
Fatal Exception: java.net.SocketTimeoutException: timeout
       at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)
       at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:684)
       at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:143)
       at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
       at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
       at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:154)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at re.notifica.internal.network.NotificareHeadersInterceptor.intercept(NotificareHeadersInterceptor.kt:23)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by hpinhal** [comment]
Hi @ali-star,

This is a network-related exception due to poor connectivity or none at all.
You're getting a crash because you're likely not handling the possible exception.

Please refer to issue #68, where this was already discussed.

**Comment by ali-star** [comment]
Thanks for the reply @hpinhal 

I wish you could put the exception handling in the SDK itself because the end developer may get confused by where exactly the crash is happening, on our project we use Notificare in a lot of places and it's hard to know where we should consider exception handling.

**Comment by hpinhal** [comment]
Hi @ali-star,

We incorporate error handling in our libraries whenever possible.

However, for cases like the one mentioned in #68, having "error handling" is impossible.
Consider you are fetching device tags (`fetchTags()`). What would the _false success_ be? An empty array?
For such cases, you want to receive the failure and handle it as you see fit.

Furthermore, if you use coroutines, any suspending function can lead to an exception.
This is part of your app's development process, and it's up to you to decide how to handle it.

**Comment by ali-star** [comment]
Hi @hpinhal 

For the `fetchTags()` function, I would create a callback so we can be sure that there will be no fatal crash, and it's a bit more developer-friendly.
There is another way by making the function return something like a Result wrapper class so the developer will know that he/she needs to handle both situations + no fatal crash anymore.

These are my suggestions as an end developer, the decision is up to you.

**Comment by hpinhal** [comment]
Hi @ali-star,

We also provide callback-based functions.
```
Notificare.device().fetchTags(object : NotificareCallback<List<String>> {
    override fun onSuccess(result: List<String>) {

    }

    override fun onFailure(e: Exception) {

    }
})
```

Designing such an API would certainly cause confusion to most developers.
Exceptions are a fundamental part of software development with which everyone is familiar.

Another thing to consider is that even though the suspending function would return such `Result<T>` type, it can still throw an exception. Suspending functions can be cancelled which throws a `CancellationException`. 

Try-catching is fundamentally necessary to prevent suspending functions from bubbling up the exception, potentially crashing your application.
