### ISSUE TITLE
Crash on app start in NotificareConfigurationProvider due tu missing key/secrete

### ISSUE THREAD

**Issue by jrtapiaO** [Notificare/notificare-sdk-android#14]
I'm trying to configure Notificare 3.1.1 installing the keys programatically. 
I do this in `Application::onCreate`, but the NotificareConfigurationProvider gets initialized before that, thus provoking a crash at the start of the app. the error is:

_Unable to get provider re.notifica.NotificareConfigurationProvider: java.lang.IllegalArgumentException: Notificare cannot be configured without an application key and secret._

stack trace:
`Caused by: java.lang.IllegalArgumentException: Notificare cannot be configured without an application key and secret.
        at re.notifica.Notificare.configure(Notificare.kt:470)
        at re.notifica.Notificare.configure(Notificare.kt:116)
        at re.notifica.Notificare.configure(Notificare.kt:96)
        at re.notifica.NotificareConfigurationProvider.onCreate(NotificareConfigurationProvider.kt:20)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1940)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1915)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6742)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6289) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6204) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) `

The documentation provided [here](https://docs.notifica.re/sdk/v3/android/customizations/) doesn's specify when or where this initialization must done. 
thanks

**Comment by hpinhal** [comment]
Hi @jrtapiaO ,

As you mentioned, the `NotificareConfigurationProvider` is initialised before the `Application` itself. Therefore it should be removed from the manifest if you're setting the keys in code.

You can add the following to the `AndroidManifest`.

```xml
<provider xmlns:tools="http://schemas.android.com/tools"
        android:name="re.notifica.NotificareConfigurationProvider"
        android:authorities="${applicationId}.NotificareConfigurationProvider"
        tools:node="remove" />
```

We'll make sure to update our documentation so it reflects this.
