### ISSUE TITLE
Crash UninitializedPropertyAccessException in NotificareGeoImpl.kt:403

### ISSUE THREAD

**Issue by narbonaMeep** [Notificare/notificare-sdk-android#201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Lot of users having the next crash:

All Devices
![image](https://github.com/user-attachments/assets/0ca100ae-058a-45a1-babf-c941d80ec3ac)
All Android versions
![image](https://github.com/user-attachments/assets/28875400-b898-4501-ac76-43a3ccf56ee1)

Using Android SDK: 4.0.0

### Steps to reproduce

We don't know how to reproduce it.
Suppect is something related to Location in background.

### Expected behaviour

Don't crash.

### Relevant log output

```sh
Fatal Exception: java.lang.RuntimeException: Unable to start receiver re.notifica.geo.gms.LocationReceiver: kotlin.UninitializedPropertyAccessException: lateinit property localStorage has not been initialized
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3614)
       at android.app.ActivityThread.access$1300(ActivityThread.java:238)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1798)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

 Caused by kotlin.UninitializedPropertyAccessException: lateinit property localStorage has not been initialized
       at re.notifica.geo.internal.NotificareGeoImpl.handleLocationUpdate(NotificareGeoImpl.kt:403)
       at re.notifica.geo.gms.LocationReceiver.onLocationUpdated(LocationReceiver.kt:47)
       at re.notifica.geo.gms.LocationReceiver.onReceive(LocationReceiver.kt:25)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3605)
       at android.app.ActivityThread.access$1300(ActivityThread.java:238)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1798)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

### Library version

4.0.0

### Operating system

Android SO - Different versions

### Smartphone model

Various models

**Comment by hpinhal** [comment]
Hi Daniel,

Can you describe how Notificare is integrated and configured in your app?
- Are you using the `notificare-services` Gradle plugin?
- Are you disabling the automatic configuration?

**Comment by hpinhal** [comment]
Hi Daniel,

As stated in our documentation,

> You should launch Notificare when the Android application is created. A small code sample can be found below.
> ...
> You can delay launching Notificare for the first time. Otherwise, make sure you launch() during the application's initialization phase to prevent missing important updates when the app is created in the background.

Given your report, you're not configuring/launching Notificare when the Android application is created.
In turn, when a geofence event wakes up your app, it will fail since the SDK was not configured.

If you're delaying the launch until some form of onboarding or opt-in takes place, that's OK for the very first install. When you enable certain features like remote notifications or geofencing, it can and will trigger events that take place early during the app's initialisation flow. Hence, you must configure & launch Notificare during the app's initialisation flow to prevent inconsistent behaviours/states.

```
class MainApplication : Application() {
    private val applicationScope = MainScope()

    override fun onCreate() {
        super.onCreate()

        applicationScope.launch {
            try {
                // Launch Notificare! 🚀
                Notificare.launch()

                // Notificare is now ready.
            } catch (e: Exception) {
                // Something went wrong ...
            }
        }
    }
}
```

**Comment by narbonaMeep** [comment]
This is our function called in onCreate in Application class.
![image](https://github.com/user-attachments/assets/4a5e51c9-63a8-448f-a5dd-e581b6f9dea9)

Also we noticed same error from re.notifica.geo.internal.NotificareGeoImpl.handleRegionEnter (NotificareGeoImpl.kt:497)
![image](https://github.com/user-attachments/assets/eea5a08e-8f0a-4f61-81e7-ba91d1bc45d5)

Any clue?

**Comment by hpinhal** [comment]
Hi Daniel,

This is not sufficient to have a clear picture of your code. For instance, the dispatcher you use influences the execution behaviour. In any case, the `configure()` cannot be inside a suspend function. Please move that to the `Application.onCreate()` as described in the documentation.

```
class MainApplication : Application() {

    override fun onCreate() {
        super.onCreate()

        Notificare.configure(
            context = applicationContext,
            applicationKey = "",
            applicationSecret = "",
        )

        // more code ...
    }
}
```

Once you make that change, you can test the app again to ensure it's being initialised correctly from a background event.

**Comment by narbonaMeep** [comment]
We moved configure part out of the suspend function and seems to be the right direction.
I will contact you again if any problem happens.
Thanks
