### ISSUE TITLE
java.lang.RuntimeExceptionGeneratedMessageLite.java:1566

### ISSUE THREAD

**Issue by baudouxbenjamin** [Notificare/notificare-sdk-android#65]
Hi, there is a crash with Notificare. Here are the logs:

```
java.lang.RuntimeException: Unable to create application com.altissia.ELanguageApplication: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7098)
        at android.app.ActivityThread.access$1500(ActivityThread.java:261)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2019)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8163)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

Caused by: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
        at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1566)
        at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1664)
        at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:957)
        at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:84)
        at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:58)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:328)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
        at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
        at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:123)
        at re.notifica.authentication.internal.storage.preferences.NotificareSharedPreferences.<init>(NotificareSharedPreferences.kt:23)
        at re.notifica.authentication.internal.NotificareAuthenticationImpl.configure(NotificareAuthenticationImpl.kt:51)
        at re.notifica.Notificare.configure(Notificare.kt:492)
        at re.notifica.Notificare.configure(Notificare.kt:118)
        at com.altissia.notificare.datasource.NotificareNotificationManager.initNotificare(NotificareNotificationManager.kt:36)
        at com.altissia.notificare.datasource.NotificareNotificationManager.initialize(NotificareNotificationManager.kt:30)
        at com.altissia.injection.module.ToolsModule$provideToolsInitializer$1.initialize(ToolsModule.kt:33)
        at com.altissia.ELanguageApplication.onCreate(ELanguageApplication.kt:35)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1195)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7093)
        at android.app.ActivityThread.access$1500(ActivityThread.java:261)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2019)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8163)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by hpinhal** [comment]
Hi @baudouxbenjamin ,

Thanks for reporting this stack trace.
To double-check, is this crashing your application, or is it just a warning?

This seems to be related to a known [bug](https://issuetracker.google.com/issues/164901843) in Google's AndroidX Security library. We're looking into possible solutions.

Can you let me know in which devices and OS versions this occurs? 

Furthermore, this boils down to using our Authentication module, which is a deprecated form of user authentication.
Most customers do not need to include this module. I would also suggest double-checking if you actually need that module.

**Comment by baudouxbenjamin** [comment]
Hi,

It crashes the application according to Bugsnag.

OS versions: 8.1.0, 9, 10, 11, 12 and 13.
Devices: Samsung, Xiaomi, Google, Huawei, Motorola, OnePlus, Lenovo and Sony. The majority of crashes happens on Samsung devices (67%).

**Comment by hpinhal** [comment]
Hi @baudouxbenjamin ,

Although we cannot reproduce this issue, it has been documented on Google's issue tracker without a clear response on whether the latest alpha version fixed it.

After looking into your applications in Notificare, the Authentication service is not enabled. Therefore, removing this module from your bundle is safe and recommended. I would only suggest ensuring you have no references to `Notificare.auth()`.

PS: Should you need to discuss confidential information regarding your account, I suggest reaching out via the [Support Portal](https://notificare.zendesk.com/).

**Comment by baudouxbenjamin** [comment]
Thanks for your time. I'll remove the authentification module then.
