### ISSUE TITLE
Gradle 8:  java.lang.IllegalArgumentException: Notificare cannot be configured without an application key and secret.

### ISSUE THREAD

**Issue by witmitchell** [Notificare/notificare-sdk-android#81]
Hello,

I try to move to Gradle wrapper 8+ and when i do so i get the following error:
```
  Caused by: java.lang.IllegalArgumentException: Notificare cannot be configured without an application key and secret.
                                                                                                    	at re.notifica.Notificare.configure(Notificare.kt:500)
                                                                                                    	at re.notifica.Notificare.configure(Notificare.kt:129)
                                                                                                    	at re.notifica.Notificare.configure(Notificare.kt:108)
                                                                                                    	at initializers.NotificareInitializer.create(NotificareInitializer.kt:17)
                                                                                                    	at app.initializers.NotificareInitializer.create(NotificareInitializer.kt:8)
                                                                                                    	at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:180)
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:238) 
                                                                                                    	at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:206) 
                                                                                                    	at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:45) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2404) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2374) 
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:7459) 
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:6976) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6747) 
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:256) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7870) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

Versions
Notificare: 3.5.2
Gradle wrapper: 8.1
Android Studio: Flamingo | 2022.2.1 Patch 1
Java version: 17

With Android Studio Electric Eel and Gradle wrapper 7.5.1 it works fine.

**Comment by witmitchell** [comment]
Thanks for your quick response.
Weird thing is the first approach worked well, until i updated AS and switched to Gradle wrapper 8+. I would like to keep using the first approach but for a workaround i will try the second approach for now.

**Comment by Y-Smirnov** [comment]
Hi @witmitchell,

If your application's approach or requirements don't require setting keys from the code, we recommend using the first approach. 

Furthermore, could you please provide a description of your migration steps and share your `build.gradle` and `gradle.settings` with us?

PS: should you need to share confidential information, please refer to the [support channel](https://notificare.zendesk.com/).

**Comment by witmitchell** [comment]
I did not apply the plugin in `app/build.gradle`. With the new Gradle this is mandatory. 
Thanks for your help!
